### ISSUE TITLE
error:23076071:PKCS12 verify failure

### ISSUE THREAD

**Issue by sysarp** [thegreenter/xmldsig#4]
```php
namespace App\Controllers\Sunat;

use Psr\Http\Message\ServerRequestInterface as Request;
use Psr\Http\Message\ResponseInterface as Response;

use Greenter\XMLSecLibs\Certificate\X509Certificate;
use Greenter\XMLSecLibs\Certificate\X509ContentType;

use App\Controllers\NsAppController;

class NsCertificadoController extends NsAppController
{
	public function pem(Request $request,Response $response){

		$pfx = file_get_contents(_APP_CDN_PATH.'/NUEVOeG9yVURJN3NOU3ZjQktQZQ==.pfx');
		$password = 'pA2kG9VVYn4M7GNE';

		$certificate = new X509Certificate($pfx,$password);
		$pem = $certificate->export(X509ContentType::PEM);
		
		file_put_contents(_APP_CDN_PATH.'/certificate.pem', $pem);
		return _APP_WSCDN.'/certificate.pem';
	}

	public function cer(Request $request,Response $response){

		$pfx = file_get_contents(_APP_CDN_PATH.'/NUEVOeG9yVURJN3NOU3ZjQktQZQ==.pfx');
		$password = 'pA2kG9VVYn4M7GNE';

		$certificate = new X509Certificate($pfx,$password);
		$cer = $certificate->export(X509ContentType::CER);

		file_put_contents(_APP_CDN_PATH.'/certificate.cer', $cer);
		return _APP_WSCDN.'/certificate.cer';
	}

}
```
Me devuelve esto alguna idea???
```
Type: Exception
Message: error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure
File: /AppServer/vendor/greenter/xmldsig/src/Certificate/X509Certificate.php
Line: 184
Trace: #0 /AppServer/vendor/greenter/xmldsig/src/Certificate/X509Certificate.php(42): Greenter\XMLSecLibs\Certificate\X509Certificate->parsePfx('0\x82,\x05\x02\x01\x030\x82+\xCB\x06\t*\x86...', 'pB2kG9VVYn4M7GN...')
#1 /AppServer/app/app/Controllers/Sunat/NsCertificadoController.php(38): Greenter\XMLSecLibs\Certificate\X509Certificate->__construct('0\x82,\x05\x02\x01\x030\x82+\xCB\x06\t*\x86...', 'pB2kG9VVYn4M7GN...')
#2 [internal function]: App\Controllers\Sunat\NsCertificadoController->cer(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /AppServer/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /AppServer/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /AppServer/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /AppServer/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /AppServer/vendor/slim/slim/Slim/App.php(515): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /AppServer/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /AppServer/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /AppServer/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /AppServer/public/app/index.php(10): Slim\App->run()
#12 {main}
```

**Comment by sysarp** [comment]
Ya esta solucionado el problema era la clave del certificado, estaba incorrecto.

**Comment by giansalex** [comment]
Que bien.
